### ISSUE TITLE
Could I use this for my particular problem I am trying to solve?

### ISSUE THREAD

**Issue by MostHated** [ByronMayne/UnityIO#4]
Hello there,
    Your asset sounds great! I was wondering if you might be able to tell me if it would be a good idea to use for what I am trying to accomplish? I have an asset currently that uses scriptableobjects to store items, items information, npc's, then also each npc's information (health, stats, etc). 

What I am wanting to do is create a web-based frontend to create new items and npc's and store them in MySQL, then have the server reach out and grab these items, npc's, values, etc and either A. if it is a change to a current scriptableobject that already exists, modify its values with the ones that were pulled from the DB. Or B. if no scriptableobject exists for the item or NPC, create a new scriptableobject with that data within the server, so that when I restart the server, the new item will be available in the game. I can then just use something like assetbundles to import any models for the particular items or NPC's, which is fine, that is pretty easy to take care of, I am just trying to figure out the best way to get these new items and NPC data into the server and have it be persistent if possible.

The goal is to be able to add new items and other things without having to rebuild and redeploy the whole server, but also not have to mess with all the individual scriptableobjects within the editor and just have the frontend generate the data, and then have something within Unity do the creation of them. 

Would using something like UnityIO be able to help me with this? I saw that it was described as "Allow of loading, creating, destroying of Unity Assets." So I am hoping that if I create a small system to actually query the DB and get the data, use something like this to be able to create the needed scriptableobjects and put them where they need to go at runtime. I am not sure if this is possible, I hope it is, but if not I need to try and find out how I can actually go about it, lol.

Sorry, it got kind of long, but hopefully, you might be able to let me know if this will help get me started toward my goal!
Thanks,
-MH

**Comment by ByronMayne** [comment]
Hey MH,

So Unity IO's goal is just to make working with the Asset Database and System.IO less of a pain the the ass. All it really is a a [Fluent API](https://en.wikipedia.org/wiki/Fluent_interface) on top of the two. Because Unity API needs project relative paths and System.IO needs full paths you end up having to do a lot of conversion which is ugly. You also have to be careful when creating folders with System.IO because the AsestDatabase does not register them right away. 

For your particular problem yes you could use Unity.IO however I think it's only help easing one of the simpler things you are trying to accomplish. The only feature that would be helpful is the conditional actions. However I don't think they have the full feature set you need. If I am correct you would need something like the following. 
`Root["Assets/Stuff/"].GetOrCreate<ScriptableObject>("PlayerStats.cs").health = 100;`
